class CourseCatalog {
  const CourseCatalog({required this.lessons});

  final List<LessonSummary> lessons;

  factory CourseCatalog.fromJson(Map<String, dynamic> json) {
    final lessons = (json['lessons'] as List<dynamic>)
        .map((item) => LessonSummary.fromJson(item as Map<String, dynamic>))
        .toList(growable: false);
    return CourseCatalog(lessons: lessons);
  }
}

class LessonSummary {
  const LessonSummary({
    required this.id,
    required this.number,
    required this.title,
    required this.date,
    this.asset,
  });

  final String id;
  final int number;
  final String title;
  final String date;
  final String? asset;

  bool get isAvailable => asset != null && asset!.isNotEmpty;

  factory LessonSummary.fromJson(Map<String, dynamic> json) {
    return LessonSummary(
      id: json['id'] as String,
      number: json['number'] as int,
      title: json['title'] as String,
      date: json['date'] as String,
      asset: json['asset'] as String?,
    );
  }
}

class Lesson {
  const Lesson({
    required this.id,
    required this.number,
    required this.title,
    required this.date,
    required this.modules,
  });

  final String id;
  final int number;
  final String title;
  final String date;
  final List<LessonModule> modules;

  int get itemCount =>
      modules.fold(0, (sum, module) => sum + module.items.length);

  factory Lesson.fromJson(Map<String, dynamic> json) {
    return Lesson(
      id: json['id'] as String,
      number: json['number'] as int,
      title: json['title'] as String,
      date: json['date'] as String,
      modules: (json['modules'] as List<dynamic>)
          .map((item) => LessonModule.fromJson(item as Map<String, dynamic>))
          .toList(growable: false),
    );
  }
}

class LessonModule {
  const LessonModule({
    required this.id,
    required this.title,
    required this.subtitle,
    required this.kind,
    required this.items,
    this.recordings = const [],
    this.image,
  });

  final String id;
  final String title;
  final String subtitle;
  final String kind;
  final List<LessonItem> items;
  final List<String> recordings;

  /// Scene picture for the module card and the top of the module.
  final String? image;

  bool get showsImage => image != null && image!.trim().isNotEmpty;

  bool get isDialogue => kind == 'dialogue';

  List<String> get sections {
    final seen = <String>[];
    for (final item in items) {
      final section = item.section;
      if (section != null && section.isNotEmpty && !seen.contains(section)) {
        seen.add(section);
      }
    }
    return seen;
  }

  /// Asset path of the teacher recording slice for [item], or null when
  /// the item has no (valid) timestamp yet.
  String? teacherAudioFor(LessonItem item) {
    final clip = item.clip;
    if (clip == null || !clip.isValid) return null;
    if (clip.recording < 0 || clip.recording >= recordings.length) return null;
    return recordings[clip.recording];
  }

  factory LessonModule.fromJson(Map<String, dynamic> json) {
    return LessonModule(
      id: json['id'] as String,
      title: json['title'] as String,
      subtitle: json['subtitle'] as String? ?? '',
      kind: json['kind'] as String? ?? 'practice',
      image: json['image'] as String?,
      recordings:
          (json['recordings'] as List<dynamic>?)
              ?.map((item) => item as String)
              .toList(growable: false) ??
          const [],
      items: (json['items'] as List<dynamic>)
          .map((item) => LessonItem.fromJson(item as Map<String, dynamic>))
          .toList(growable: false),
    );
  }
}

class LessonItem {
  const LessonItem({
    required this.id,
    required this.type,
    required this.cantonese,
    required this.jyutping,
    required this.mandarin,
    this.speaker,
    this.section,
    this.note,
    this.image,
    this.clip,
    this.fill = const [],
  });

  final String id;
  final String type;
  final String cantonese;
  final String jyutping;
  final String mandarin;
  final String? speaker;
  final String? section;
  final String? note;

  /// Asset path for a picture on a vocabulary card, such as
  /// `assets/glossary/toast.png`. Phrase cards ignore it.
  final String? image;

  /// Teacher-recording slice for this sentence, auto-generated by the
  /// alignment script (`tools/align/`). When present, the card offers
  /// teacher-audio playback without needing device TTS.
  final AudioClip? clip;

  /// Fill-in-the-blank specs, in the order blanks (`__`/`___`) appear in
  /// [cantonese]. Lets learners tap a blank and enter their own info
  /// (name, phone number, date) instead of reading underscores.
  final List<BlankSpec> fill;

  bool get showsImage =>
      type == 'vocab' && image != null && image!.trim().isNotEmpty;

  bool get hasTeacherClip => clip != null;

  String get speakText => cantonese;

  factory LessonItem.fromJson(Map<String, dynamic> json) {
    return LessonItem(
      id: json['id'] as String,
      type: json['type'] as String? ?? 'phrase',
      cantonese: json['cantonese'] as String,
      jyutping: json['jyutping'] as String,
      mandarin: json['mandarin'] as String,
      speaker: json['speaker'] as String?,
      section: json['section'] as String?,
      note: json['note'] as String?,
      image: json['image'] as String?,
      clip: json['clip'] == null
          ? null
          : AudioClip.fromJson(json['clip'] as Map<String, dynamic>),
      fill:
          (json['fill'] as List<dynamic>?)
              ?.map((spec) => BlankSpec.fromJson(spec as Map<String, dynamic>))
              .toList(growable: false) ??
          const [],
    );
  }
}

/// One fillable blank in a lesson sentence.
class BlankSpec {
  const BlankSpec({required this.kind, this.fallback, this.options = const []});

  final BlankKind kind;

  /// Shown before the learner saves their own value. Origin blanks use
  /// this so the sentence still reads 「北京人」 until they change it.
  final String? fallback;

  /// Suggested values. The sheet also keeps a free-text field.
  final List<String> options;

  factory BlankSpec.fromJson(Map<String, dynamic> json) {
    final rawOptions = json['options'] as List<dynamic>?;
    return BlankSpec(
      kind: BlankKind.parse(json['kind'] as String?),
      fallback: json['fallback'] as String?,
      options:
          rawOptions
              ?.map((option) => option as String)
              .toList(growable: false) ??
          const [],
    );
  }
}

/// Blank editors: free text (name), digits (phone/month/day),
/// Suggested hometowns for the origin blank and the opening question.
const kOriginSuggestions = <String>[
  '北京人',
  '上海人',
  '廣州人',
  '深圳人',
  '香港人',
  '台灣人',
  '福建人',
];

/// weekday picker, or an origin with suggestions plus free text.
enum BlankKind {
  name,
  phone,
  month,
  day,
  weekday,
  origin,
  other;

  static BlankKind parse(String? raw) {
    return BlankKind.values.firstWhere(
      (kind) => kind.name == raw,
      orElse: () => BlankKind.other,
    );
  }
}

/// A slice of a teacher recording in [LessonModule.recordings].
///
/// Times are milliseconds from the start of the file. `recording` is the
/// index into the module's `recordings` list (0 when the module has one).
class AudioClip {
  const AudioClip({
    required this.startMs,
    required this.endMs,
    this.recording = 0,
    this.words,
  });

  final int startMs;
  final int endMs;
  final int recording;

  /// Optional per-character timings for karaoke highlighting.
  final WordTiming? words;

  Duration get start => Duration(milliseconds: startMs);
  Duration get end => Duration(milliseconds: endMs);
  Duration get length => end - start;

  bool get isValid => endMs > startMs && startMs >= 0 && recording >= 0;

  factory AudioClip.fromJson(Map<String, dynamic> json) {
    return AudioClip(
      startMs: (json['startMs'] as num).toInt(),
      endMs: (json['endMs'] as num).toInt(),
      recording: (json['rec'] as num?)?.toInt() ?? 0,
      words: WordTiming.tryParse(json['words']),
    );
  }

  Map<String, dynamic> toJson() => {
    if (recording != 0) 'rec': recording,
    'startMs': startMs,
    'endMs': endMs,
    if (words != null) 'words': words!.toJson(),
  };
}

/// Per-character timings inside an [AudioClip], in recording-absolute
/// milliseconds, produced by `tools/align/extract_words.py`.
///
/// [text] is the plain-normalized display text (punctuation stripped,
/// lowercased — see [normalizeKaraokeText]); [startsMs]/[endsMs] run
/// parallel to its characters and drive karaoke highlighting.
class WordTiming {
  const WordTiming({
    required this.text,
    required this.startsMs,
    required this.endsMs,
  });

  final String text;
  final List<int> startsMs;
  final List<int> endsMs;

  int get length => text.length;

  bool get isValid =>
      text.isNotEmpty &&
      startsMs.length == text.length &&
      endsMs.length == text.length;

  /// Null when the payload is missing or malformed — callers fall back
  /// to sentence-level highlighting instead of crashing lesson load.
  static WordTiming? tryParse(dynamic json) {
    try {
      if (json is! Map<String, dynamic>) return null;
      final text = json['t'] as String? ?? '';
      final raw = json['w'] as List<dynamic>? ?? const [];
      final starts = <int>[];
      final ends = <int>[];
      for (var i = 0; i + 1 < raw.length; i += 2) {
        starts.add((raw[i] as num).toInt());
        ends.add((raw[i + 1] as num).toInt());
      }
      final timing = WordTiming(
        text: text,
        startsMs: List.unmodifiable(starts),
        endsMs: List.unmodifiable(ends),
      );
      return timing.isValid ? timing : null;
    } catch (_) {
      return null;
    }
  }

  Map<String, dynamic> toJson() => {
    't': text,
    'w': [
      for (var i = 0; i < startsMs.length; i++) ...[startsMs[i], endsMs[i]],
    ],
  };
}
